### PR TITLE
Add Logic to Filter Out Self-Imports

### PR DESCRIPTION
**Pull request by gyrfalcon**
Added code to prevent symbols from the current file from being imported.
Also tweaked baseDir handling to make it better.

### CODE REVIEW

**Comment by LoganBarnett** [comment]
How do you feel about some kind of test to verify these changes? Things are still pretty rough in the test department, so it's fine if it seems like a lot :)

**Comment by gyrfalcon** [comment]
Yeah, I can see about doing up a test for this. It may take me a day or two to get to it.

**Comment by gyrfalcon** [comment]
I added some tests for the import piece, I also brought in a generator for reusing refiners, currently named `degenRefiner`, for refiner reuse (and also it helped with testing). I'm not set on the name, suggestions welcome.

I haven't figured out how to test the baseDir changes yet.

**Comment by gyrfalcon** [comment]
Got a test for the prepending of baseDir that occurs in `base-gen.js` in place now.

**Comment by LoganBarnett** [comment]
I like `degenRefiner` better than our earlier attempts. Thanks!!

**Pull request merged**
